// GENERATED by bin/generate_pricing_targets.dart — do not
// hand-edit. Re-run the generator and review the diff.
//
// The reviewed pricing source for BOTH stores: anchor currencies
// (USD/EUR/GBP) at the USD nominal, every other currency at
// Google's convertRegionPrices table (regionVersion
// 2026/01 — FX-current, tax-aware, market-rounded).
// asc-products snaps each value to the nearest App Store price
// point; play-products writes the exact value per region.
//
// Policy decisions baked in:
// - CNY: no Google reference (no Play in China) — keeps
//   Apple's mainland-China market pricing.
// - CHF: CH and LI price differently on Google — per-territory
//   rows below (CHE/LIE on ASC, CH/LI on Play).
// - iOS lifetime (pro_lifetime) is NOT driven by this table:
//   its auto-equalized price schedule is FX-current and
//   Apple maintains it (verified 2026-10).
/// Reviewed pricing targets — see the header above.
class PricingTargets {
  PricingTargets._();

  static const monthlyUsd = '4.99';
  static const yearlyUsd = '49.99';
  static const lifetimeUsd = '99.99';

  /// The Google convertRegionPrices table version these values
  /// came from — Play writes must pass a current regionVersion
  /// (an older one is rejected for regions whose currency
  /// changed since).
  static const googleTableVersion = '2026/01';

  /// Currencies kept at the USD nominal (4.99/49.99/99.99).
  static const anchorCurrencies = {'USD', 'EUR', 'GBP'};

  /// (monthly, yearly, lifetime) per non-anchor currency.
  static const byCurrency = <String, (String, String, String)>{
    'AED': ('18.99', '194.99', '384.99'),
    'ARS': ('7600', '76100', '152000'),
    'AUD': ('7.99', '78.99', '159.99'),
    'AZN': ('8.49', '84.99', '169.99'),
    'BDT': ('700', '7100', '14000'),
    'BOB': ('58.99', '589.99', '1189.99'),
    'BRL': ('25.99', '259.99', '519.99'),
    'CAD': ('6.99', '70.99', '144.99'),
    'CLP': ('5900', '59000', '118000'),
    'COP': ('16500', '163000', '327000'),
    'CRC': ('2300', '22900', '45800'),
    'CZK': ('129.99', '1299.99', '2599.99'),
    'DKK': ('41', '415', '829'),
    'DZD': ('675', '6700', '13375'),
    'EGP': ('299.99', '2999.99', '5949.99'),
    'ETB': ('800', '8100', '16100'),
    'GEL': ('14', '149', '299'),
    'GHS': ('70', '700', '1400'),
    'HKD': ('39.90', '389', '788'),
    'HUF': ('2090', '20999', '41499'),
    'IDR': ('89000', '890000', '1790000'),
    'ILS': ('15', '149.90', '299.90'),
    'INR': ('550', '5700', '11400'),
    'IQD': ('6550', '65500', '131000'),
    'JOD': ('3.55', '35.40', '71'),
    'JPY': ('860', '8700', '17400'),
    'KES': ('800', '7500', '15000'),
    'KRW': ('7500', '75000', '150000'),
    'KZT': ('2590', '25990', '51990'),
    'LKR': ('1650', '16500', '33000'),
    'MAD': ('58.99', '599.99', '1189.99'),
    'MMK': ('10000', '105000', '210000'),
    'MNT': ('17900', '179800', '359500'),
    'MOP': ('39.99', '408', '808'),
    'MXN': ('105', '1049', '2099'),
    'MYR': ('21.99', '219.99', '439.99'),
    'NGN': ('7140', '71500', '143000'),
    'NOK': ('59', '599', '1199'),
    'NZD': ('9.99', '99.99', '204.99'),
    'PEN': ('16.99', '169.99', '344.99'),
    'PHP': ('350', '3500', '7000'),
    'PKR': ('1400', '13900', '27700'),
    'PLN': ('23.99', '239.99', '479.99'),
    'PYG': ('30000', '300000', '600000'),
    'QAR': ('18', '180', '365'),
    'RON': ('28.99', '284.99', '549.99'),
    'RSD': ('649', '6499', '12999'),
    'RUB': ('419', '4199', '8399'),
    'SAR': ('21.99', '214.99', '429.99'),
    'SEK': ('65', '629', '1249'),
    'SGD': ('6.98', '69.98', '139.98'),
    'THB': ('175', '1800', '3600'),
    'TRY': ('294.99', '2949.99', '5899.99'),
    'TWD': ('170', '1670', '3350'),
    'TZS': ('13000', '132000', '264000'),
    'UAH': ('269.99', '2699.99', '5399.99'),
    'UZS': ('65820', '659400', '1319000'),
    'VND': ('130000', '1300000', '2600000'),
    'XAF': ('3500', '34700', '69500'),
    'XOF': ('3400', '34400', '68800'),
    'ZAR': ('95.99', '959.99', '1899.99'),
    // No Google reference — Apple's mainland-China market pricing.
    'CNY': ('26', '222', '698'),
  };

  /// Per-region rows where a currency's regions disagree.
  /// Keys are Play region codes; the identical ISO-3 codes
  /// (CHE/LIE) address the ASC territories.
  static const byRegion = <String, (String, String, String)>{
    'CH': ('4.10', '41', '85'),
    'LI': ('4.50', '45', '90'),
  };

  /// Play region → currency (from the Google table).
  static const playRegionCurrency = <String, String>{
    'AE': 'AED',
    'AG': 'USD',
    'AL': 'USD',
    'AM': 'USD',
    'AO': 'USD',
    'AR': 'ARS',
    'AT': 'EUR',
    'AU': 'AUD',
    'AW': 'USD',
    'AZ': 'AZN',
    'BA': 'USD',
    'BD': 'BDT',
    'BE': 'EUR',
    'BF': 'EUR',
    'BG': 'EUR',
    'BH': 'USD',
    'BJ': 'EUR',
    'BM': 'USD',
    'BO': 'BOB',
    'BR': 'BRL',
    'BS': 'USD',
    'BW': 'USD',
    'BY': 'USD',
    'BZ': 'USD',
    'CA': 'CAD',
    'CD': 'USD',
    'CF': 'EUR',
    'CG': 'USD',
    'CH': 'CHF',
    'CI': 'XOF',
    'CL': 'CLP',
    'CM': 'XAF',
    'CO': 'COP',
    'CR': 'CRC',
    'CV': 'USD',
    'CY': 'EUR',
    'CZ': 'CZK',
    'DE': 'EUR',
    'DJ': 'USD',
    'DK': 'DKK',
    'DM': 'USD',
    'DO': 'USD',
    'DZ': 'DZD',
    'EC': 'USD',
    'EE': 'EUR',
    'EG': 'EGP',
    'ER': 'USD',
    'ES': 'EUR',
    'ET': 'ETB',
    'FI': 'EUR',
    'FJ': 'USD',
    'FM': 'USD',
    'FR': 'EUR',
    'GA': 'EUR',
    'GB': 'GBP',
    'GD': 'USD',
    'GE': 'GEL',
    'GH': 'GHS',
    'GI': 'GBP',
    'GM': 'USD',
    'GN': 'USD',
    'GR': 'EUR',
    'GT': 'USD',
    'GW': 'EUR',
    'HK': 'HKD',
    'HN': 'USD',
    'HR': 'EUR',
    'HT': 'USD',
    'HU': 'HUF',
    'ID': 'IDR',
    'IE': 'EUR',
    'IL': 'ILS',
    'IN': 'INR',
    'IQ': 'IQD',
    'IS': 'EUR',
    'IT': 'EUR',
    'JM': 'USD',
    'JO': 'JOD',
    'JP': 'JPY',
    'KE': 'KES',
    'KG': 'USD',
    'KH': 'USD',
    'KM': 'USD',
    'KN': 'USD',
    'KR': 'KRW',
    'KW': 'USD',
    'KY': 'USD',
    'KZ': 'KZT',
    'LA': 'USD',
    'LB': 'USD',
    'LC': 'USD',
    'LI': 'CHF',
    'LK': 'LKR',
    'LR': 'USD',
    'LT': 'EUR',
    'LU': 'EUR',
    'LV': 'EUR',
    'LY': 'USD',
    'MA': 'MAD',
    'MC': 'EUR',
    'MD': 'USD',
    'MK': 'USD',
    'ML': 'EUR',
    'MM': 'MMK',
    'MN': 'MNT',
    'MO': 'MOP',
    'MT': 'EUR',
    'MU': 'USD',
    'MV': 'USD',
    'MX': 'MXN',
    'MY': 'MYR',
    'MZ': 'USD',
    'NA': 'USD',
    'NE': 'EUR',
    'NG': 'NGN',
    'NI': 'USD',
    'NL': 'EUR',
    'NO': 'NOK',
    'NP': 'USD',
    'NZ': 'NZD',
    'OM': 'USD',
    'PA': 'USD',
    'PE': 'PEN',
    'PG': 'USD',
    'PH': 'PHP',
    'PK': 'PKR',
    'PL': 'PLN',
    'PT': 'EUR',
    'PY': 'PYG',
    'QA': 'QAR',
    'RO': 'RON',
    'RS': 'RSD',
    'RU': 'RUB',
    'RW': 'USD',
    'SA': 'SAR',
    'SB': 'USD',
    'SC': 'USD',
    'SE': 'SEK',
    'SG': 'SGD',
    'SI': 'EUR',
    'SK': 'EUR',
    'SL': 'USD',
    'SM': 'EUR',
    'SN': 'XOF',
    'SO': 'USD',
    'SR': 'USD',
    'SV': 'USD',
    'TC': 'USD',
    'TD': 'USD',
    'TG': 'EUR',
    'TH': 'THB',
    'TJ': 'USD',
    'TM': 'USD',
    'TN': 'USD',
    'TO': 'USD',
    'TR': 'TRY',
    'TT': 'USD',
    'TW': 'TWD',
    'TZ': 'TZS',
    'UA': 'UAH',
    'UG': 'USD',
    'US': 'USD',
    'UY': 'USD',
    'UZ': 'UZS',
    'VA': 'EUR',
    'VE': 'USD',
    'VG': 'USD',
    'VN': 'VND',
    'VU': 'USD',
    'WS': 'USD',
    'YE': 'USD',
    'ZA': 'ZAR',
    'ZM': 'USD',
    'ZW': 'USD',
  };

  /// The target price string for [currency] and a product
  /// identified by its USD nominal, honouring per-territory
  /// overrides. Null when neither covers it.
  static String? target(String currency, String priceUsd, {String? region}) {
    final row =
        (region != null ? byRegion[region] : null) ??
        byCurrency[currency];
    if (row == null) {
      if (!anchorCurrencies.contains(currency)) return null;
      return switch (priceUsd) {
        monthlyUsd => monthlyUsd,
        yearlyUsd => yearlyUsd,
        lifetimeUsd => lifetimeUsd,
        _ => null,
      };
    }
    return switch (priceUsd) {
      monthlyUsd => row.$1,
      yearlyUsd => row.$2,
      lifetimeUsd => row.$3,
      _ => null,
    };
  }
}
