// GENERATED by tool/youtube_emoji_harvest/harvest.py - do not edit by hand.
//
// YouTube's standard live-chat emojis (owner channel UCkszU2WH9gy1mb0dV-11UJg): the
// Data API only sends their `:shortcode:`, the image exists only in the
// web chat data. The app learns more at runtime (`YouTubeEmojiStore`).

import 'youtube_emoji.dart';

const List<YouTubeStandardEmoji> kYouTubeStandardEmojis = [
  YouTubeStandardEmoji(
    id: '4PgfY73cJprKCq-_gIAO',
    codes: [':body-green-covering-eyes:'],
    url: 'https://yt3.ggpht.com/UR8ydcU3gz360bzDsprB6d1klFSQyVzgn-Fkgu13dIKPj3iS8OtG1bhBUXPdj9pMwtM00ro',
  ),
  YouTubeStandardEmoji(
    id: 'X_zdXMHgJaPa8gTGt4f4Ag',
    codes: [':buffering:'],
    url: 'https://yt3.ggpht.com/5gfMEfdqO9CiLwhN9Mq7VI6--T2QFp8AXNNy5Fo7btfY6fRKkThWq35SCZ6SPMVCjg-sUA',
  ),
  YouTubeStandardEmoji(
    id: 'E8MfY5u7JPSXkNAP95GAmAE',
    codes: [':cat-orange-whistling:'],
    url: 'https://yt3.ggpht.com/0ocqEmuhrKCK87_J21lBkvjW70wRGC32-Buwk6TP4352CgcNjL6ug8zcsel6JiPbE58xhq5g',
  ),
  YouTubeStandardEmoji(
    id: 'jPgfY5j2IIud29sP3ZeA4Ag',
    codes: [':eyes-pink-heart-shape:'],
    url: 'https://yt3.ggpht.com/5vzlCQfQQdzsG7nlQzD8eNjtyLlnATwFwGvrMpC8dgLcosNhWLXu8NN9qIS3HZjJYd872dM',
  ),
  YouTubeStandardEmoji(
    id: '7cIfY5niDOmSkNAP08CA6A4',
    codes: [':eyes-purple-crying:'],
    url: 'https://yt3.ggpht.com/FrYgdeZPpvXs-6Mp305ZiimWJ0wV5bcVZctaUy80mnIdwe-P8HRGYAm0OyBtVx8EB9_Dxkc',
  ),
  YouTubeStandardEmoji(
    id: 'LfkfY_zhH4GFr8oP4aKA6AI',
    codes: [':face-blue-question-mark:'],
    url: 'https://yt3.ggpht.com/Wx4PMqTwG3f4gtR7J9Go1s8uozzByGWLSXHzrh3166ixaYRinkH_F05lslfsRUsKRvHXrDk',
  ),
  YouTubeStandardEmoji(
    id: 'KsIfY6LzFoLM6AKanYDQAg',
    codes: [':face-blue-smiling:'],
    url: 'https://yt3.ggpht.com/cktIaPxFwnrPwn-alHvnvedHLUJwbHi8HCK3AgbHpphrMAW99qw0bDfxuZagSY5ieE9BBrA',
  ),
  YouTubeStandardEmoji(
    id: 'mW5IY47PMcSnkMkPo6OAyAk',
    codes: [':face-blue-three-eyes:'],
    url: 'https://yt3.ggpht.com/nSQHitVplLe5uZC404dyAwv1f58S3PN-U_799fvFzq-6b3bv-MwENO-Zs1qQI4oEXCbOJg',
  ),
  YouTubeStandardEmoji(
    id: 'LsMfY8P6G-yckNAPjoWA8AI',
    codes: [':face-blue-wide-eyes:'],
    url: 'https://yt3.ggpht.com/2Ht4KImoWDlCddiDQVuzSJwpEb59nZJ576ckfaMh57oqz2pUkkgVTXV8osqUOgFHZdUISJM',
  ),
  YouTubeStandardEmoji(
    id: 'xsIfY4OqCd2T29sP54iAsAw',
    codes: [':face-green-smiling:'],
    url: 'https://yt3.ggpht.com/G061SAfXg2bmG1ZXbJsJzQJpN8qEf_W3f5cb5nwzBYIV58IpPf6H90lElDl85iti3HgoL3o',
  ),
  YouTubeStandardEmoji(
    id: 'ygF1XpGUMMjk8gSDrI2wCx',
    codes: [':face-orange-biting-nails:'],
    url: 'https://yt3.ggpht.com/HmsXEgqUogkQOnL5LP_FdPit9Z909RJxby-uYcPxBLNhaPyqPTcGwvGaGPk2hzB_cC0hs_pV',
  ),
  YouTubeStandardEmoji(
    id: '2sIfY8vIG8z96ALulYDQDQ',
    codes: [':face-orange-frowning:'],
    url: 'https://yt3.ggpht.com/Ar8jaEIxzfiyYmB7ejDOHba2kUMdR37MHn_R39mtxqO5CD4aYGvjDFL22DW_Cka6LKzhGDk',
  ),
  YouTubeStandardEmoji(
    id: 'Z8MfY8mzLbnovwK5roC4Bg',
    codes: [':face-orange-raised-eyebrow:'],
    url: 'https://yt3.ggpht.com/JbCfmOgYI-mO17LPw8e_ycqbBGESL8AVP6i7ZsBOVLd3PEpgrfEuJ9rEGpP_unDcqgWSCg',
  ),
  YouTubeStandardEmoji(
    id: 'b8IfY7zOK9iVkNAP_I2A-AY',
    codes: [':face-purple-crying:'],
    url: 'https://yt3.ggpht.com/g6_km98AfdHbN43gvEuNdZ2I07MmzVpArLwEvNBwwPqpZYzszqhRzU_DXALl11TchX5_xFE',
  ),
  YouTubeStandardEmoji(
    id: 'Ym5IY7-0LoqA29sPq9CAkAY',
    codes: [':face-purple-smiling-tears:'],
    url: 'https://yt3.ggpht.com/MJV1k3J5s0hcUfuo78Y6MKi-apDY5NVDjO9Q7hL8fU4i0cIBgU-cU4rq4sHessJuvuGpDOjJ',
  ),
  YouTubeStandardEmoji(
    id: 'W8IfY_bwAfiPq7IPvNCA2AU',
    codes: [':face-red-droopy-eyes:'],
    url: 'https://yt3.ggpht.com/oih9s26MOYPWC_uL6tgaeOlXSGBv8MMoDrWzBt-80nEiVSL9nClgnuzUAKqkU9_TWygF6CI',
  ),
  YouTubeStandardEmoji(
    id: 'm8MfY4jbFsWJhL0PyouA2Ak',
    codes: [':face-red-heart-shape:'],
    url: 'https://yt3.ggpht.com/I0Mem9dU_IZ4a9cQPzR0pUJ8bH-882Eg0sDQjBmPcHA6Oq0uXOZcsjPvPbtormx91Ha2eRA',
  ),
  YouTubeStandardEmoji(
    id: 'oPgfY_DoKfSXkNAPq8-AgAo',
    codes: [':face-turquoise-covering-eyes:'],
    url: 'https://yt3.ggpht.com/H2HNPRO8f4SjMmPNh5fl10okSETW7dLTZtuE4jh9D6pSmaUiLfoZJ2oiY-qWU3Owfm1IsXg',
  ),
  YouTubeStandardEmoji(
    id: 'finger-red-number-one',
    codes: [':finger-red-number-one:'],
    url: 'https://yt3.ggpht.com/Hbk0wxBzPTBCDvD_y4qdcHL5_uu7SeOnaT2B7gl9GLB4u8Ecm9OaXCGSMMUBFeNGl5Q3fHJ2',
  ),
  YouTubeStandardEmoji(
    id: '-fgfY9DIGYjbhgHLzoDIDw',
    codes: [':goat-turquoise-white-horns:'],
    url: 'https://yt3.ggpht.com/jMnX4lu5GnjBRgiPtX5FwFmEyKTlWFrr5voz-Auko35oP0t3-zhPxR3PQMYa-7KhDeDtrv4',
  ),
  YouTubeStandardEmoji(
    id: 'YvgfY-LIBpjChgHKyYCQBg',
    codes: [':hand-orange-covering-eyes:'],
    url: 'https://yt3.ggpht.com/y8ppa6GcJoRUdw7GwmjDmTAnSkeIkUptZMVQuFmFaTlF_CVIL7YP7hH7hd0TJbd8p9w67IM',
  ),
  YouTubeStandardEmoji(
    id: 'G8AfY6yWGuKuhL0PlbiA2AE',
    codes: [':hand-pink-waving:'],
    url: 'https://yt3.ggpht.com/KOxdr_z3A5h1Gb7kqnxqOCnbZrBmxI2B_tRQ453BhTWUhYAlpg5ZP8IKEBkcvRoY8grY91Q',
  ),
  YouTubeStandardEmoji(
    id: 'fAF1XtDQMIrK8gTUoo3wAg',
    codes: [':hydrate:'],
    url: 'https://yt3.ggpht.com/tpgZgmhX8snKniye36mnrDVfTnlc44EK92EPeZ0m9M2EPizn1vKEGJzNYdp7KQy6iNZlYDc1',
  ),
  YouTubeStandardEmoji(
    id: 'medal-yellow-first-red',
    codes: [':medal-yellow-first-red:'],
    url: 'https://yt3.ggpht.com/EEHiiIalCBKuWDPtNOjjvmEZ-KRkf5dlgmhe5rbLn8aZQl-pNz_paq5UjxNhCrI019TWOQ',
  ),
  YouTubeStandardEmoji(
    id: 'ssIfY7OFG5OykQOpn4CQCw',
    codes: [':person-turqouise-waving:'],
    url: 'https://yt3.ggpht.com/uNSzQ2M106OC1L3VGzrOsGNjopboOv-m1bnZKFGuh0DxcceSpYHhYbuyggcgnYyaF3o-AQ',
  ),
  YouTubeStandardEmoji(
    id: 'lP90XvOhCZGl8wSO1JmgAw',
    codes: [':sanitizer:'],
    url: 'https://yt3.ggpht.com/EJ_8vc4Gl-WxCWBurHwwWROAHrPzxgePodoNfkRY1U_I8L1O2zlqf7-wfUtTeyzq2qHNnocZ',
  ),
  YouTubeStandardEmoji(
    id: '1v50XorRJ8GQ8gTz_prwAg',
    codes: [':stayhome:'],
    url: 'https://yt3.ggpht.com/_1FGHypiub51kuTiNBX1a0H3NyFih3TnHX7bHU06j_ajTzT0OQfMLl9RI1SiQoxtgA2Grg',
  ),
  YouTubeStandardEmoji(
    id: 'hcIfY57lBJXp6AKBx4CoCA',
    codes: [':text-green-game-over:'],
    url: 'https://yt3.ggpht.com/cr36FHhSiMAJUSpO9XzjbOgxhtrdJNTVJUlMJeOOfLOFzKleAKT2SEkZwbqihBqfTXYCIg',
  ),
  YouTubeStandardEmoji(
    id: 'Rf90XtDbG8GQ8gTz_prwAg',
    codes: [':thanksdoc:'],
    url: 'https://yt3.ggpht.com/bUnO_VwXW2hDf-Da8D64KKv6nBJDYUBuo13RrOg141g2da8pi9-KClJYlUDuqIwyPBfvOO8',
  ),
  YouTubeStandardEmoji(
    id: 'ePgfY-K2Kp6Mr8oP1oqAwAc',
    codes: [':trophy-yellow-smiling:'],
    url: 'https://yt3.ggpht.com/7tf3A_D48gBg9g2N0Rm6HWs2aqzshHU4CuVubTXVxh1BP7YDBRC6pLBoC-ibvr-zCl_Lgg',
  ),
  YouTubeStandardEmoji(
    id: 'dv90XtfhAurw8gTgzar4DA',
    codes: [':virtualhug:'],
    url: 'https://yt3.ggpht.com/U1TjOZlqtS58NGqQhE8VWDptPSrmJNkrbVRp_8jI4f84QqIGflq2Ibu7YmuOg5MmVYnpevc',
  ),
  YouTubeStandardEmoji(
    id: 'whistle-red-blow',
    codes: [':whistle-red-blow:'],
    url: 'https://yt3.ggpht.com/DBu1ZfPJTnX9S1RyKKdBY-X_CEmj7eF6Uzl71j5jVBz5y4k9JcKnoiFtImAbeu4u8M2X8tU',
  ),
  YouTubeStandardEmoji(
    id: 'CIW60IPp_dYCFcuqTgodEu4IlQ',
    codes: [':yt:'],
    url: 'https://yt3.ggpht.com/IkpeJf1g9Lq0WNjvSa4XFq4LVNZ9IP5FKW8yywXb12djo1OGdJtziejNASITyq4L0itkMNw',
  ),
];
