import 'dart:convert';

/// Channel that owns YouTube's standard live-chat emojis (`:yt:`,
/// `:face-blue-smiling:`, `:medal-yellow-first-red:`, ...) - everyone can
/// use them. Any other owner is a channel's member emoji.
const String kYouTubeStandardEmojiOwner = 'UCkszU2WH9gy1mb0dV-11UJg';

/// A bundled standard emoji (`youtube_standard_emojis.dart`, generated by
/// `tool/youtube_emoji_harvest/`).
class YouTubeStandardEmoji {
  final String id;
  final List<String> codes;

  /// Image URL without the size suffix
  final String url;

  const YouTubeStandardEmoji({
    required this.id,
    required this.codes,
    required this.url,
  });
}

/// One YouTube live-chat emoji: YouTube's standard set or a channel's
/// member emoji. The Data API sends only the `:code:` text - the image
/// comes from the web chat's data (`parseYouTubeEmojis`) or the bundle.
class YouTubeEmoji {
  /// `<owner channel id>/<emoji id>`
  final String id;

  /// Every `:code:` that writes it (member emojis have several, e.g.
  /// `:_addiOmg:`, `:addiOmg:`, `:_omg:`, `:omg:`)
  final List<String> codes;

  /// Image URL without the size suffix (yt3.ggpht.com takes `=w<n>-h<n>`)
  final String imageBase;

  const YouTubeEmoji({
    required this.id,
    required this.codes,
    required this.imageBase,
  });

  String get ownerChannelId => this.id.split('/').first;

  bool get isStandard => this.ownerChannelId == kYouTubeStandardEmojiOwner;

  /// The code the picker inserts - the first one YouTube lists
  String get code => this.codes.first;

  /// Square image of [pixels] (physical) - ggpht scales server-side
  String imageUrl(int pixels) => '${this.imageBase}=w$pixels-h$pixels-c-k-nd';

  Map<String, Object?> toJson() => {
    'id': this.id,
    'codes': this.codes,
    'image': this.imageBase,
  };

  static YouTubeEmoji? fromJson(Object? json) {
    if (json is! Map) return null;
    final id = json['id'];
    final codes = json['codes'];
    final image = json['image'];
    if (id is! String || codes is! List || image is! String) return null;
    final list = [
      for (final code in codes)
        if (code is String && code.isNotEmpty) code,
    ];
    if (list.isEmpty) return null;
    return YouTubeEmoji(id: id, codes: list, imageBase: image);
  }

  static YouTubeEmoji fromStandard(YouTubeStandardEmoji emoji) => YouTubeEmoji(
    id: '$kYouTubeStandardEmojiOwner/${emoji.id}',
    codes: emoji.codes,
    imageBase: emoji.url,
  );
}

/// A `:code:` in chat text: letters, digits, `_` and `-`, at least one
/// letter (so clock times like `10:30:45` never match).
final RegExp kYouTubeEmojiCodePattern = RegExp(
  r':(?=[A-Za-z0-9_-]*[A-Za-z])[A-Za-z0-9_-]+:',
);

/// The image URL without its size suffix (`...=w48-h48-c-k-nd`).
String youTubeEmojiImageBase(String url) => url.split('=').first;

/// Every custom emoji (standard or member) in a YouTube web live-chat
/// page (`/live_chat?v=`): message runs carry `{emojiId, shortcuts,
/// image.thumbnails, isCustomEmoji: true}` (captured 2026-10-04, see
/// `docs/youtube-native-chat-audit.md`). Unicode emoji (`isCustomEmoji`
/// absent) are skipped - the text already has the character.
List<YouTubeEmoji> parseYouTubeEmojis(String html) {
  final match =
      RegExp(
        r'ytInitialData"\]\s*=\s*(\{.*?\});\s*</script>',
        dotAll: true,
      ).firstMatch(html) ??
      RegExp(
        r'ytInitialData\s*=\s*(\{.*?\});\s*</script>',
        dotAll: true,
      ).firstMatch(html);
  if (match == null) return const [];
  final Object? data;
  try {
    data = json.decode(match.group(1)!);
  } catch (_) {
    return const [];
  }
  final found = <String, YouTubeEmoji>{};
  void walk(Object? node) {
    if (node is Map) {
      if (node['isCustomEmoji'] == true && node['emojiId'] is String) {
        final shortcuts = node['shortcuts'];
        final thumbs = (node['image'] as Map?)?['thumbnails'];
        if (shortcuts is List && thumbs is List && thumbs.isNotEmpty) {
          final url = (thumbs.last as Map?)?['url'];
          final codes = [
            for (final code in shortcuts)
              if (code is String && code.isNotEmpty) code,
          ];
          if (url is String && codes.isNotEmpty) {
            final id = node['emojiId'] as String;
            found[id] = YouTubeEmoji(
              id: id,
              codes: codes,
              imageBase: youTubeEmojiImageBase(url),
            );
          }
        }
      }
      for (final value in node.values) {
        walk(value);
      }
    } else if (node is List) {
      for (final value in node) {
        walk(value);
      }
    }
  }

  walk(data);
  return found.values.toList();
}
