// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive_ce.dart';
import 'package:obs_blade/models/app_log.dart';
import 'package:obs_blade/models/connection.dart';
import 'package:obs_blade/models/custom_theme.dart';
import 'package:obs_blade/models/enums/chat_type.dart';
import 'package:obs_blade/models/enums/dashboard_element.dart';
import 'package:obs_blade/models/enums/log_level.dart';
import 'package:obs_blade/models/enums/scene_item_type.dart';
import 'package:obs_blade/models/hidden_scene.dart';
import 'package:obs_blade/models/hidden_scene_item.dart';
import 'package:obs_blade/models/hotkey.dart';
import 'package:obs_blade/models/past_record_data.dart';
import 'package:obs_blade/models/past_stream_data.dart';
import 'package:obs_blade/models/purchased_tip.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(AppLogAdapter());
    registerAdapter(ChatTypeAdapter());
    registerAdapter(ConnectionAdapter());
    registerAdapter(CustomThemeAdapter());
    registerAdapter(DashboardElementAdapter());
    registerAdapter(HiddenSceneAdapter());
    registerAdapter(HiddenSceneItemAdapter());
    registerAdapter(HotkeyAdapter());
    registerAdapter(LogLevelAdapter());
    registerAdapter(PastRecordDataAdapter());
    registerAdapter(PastStreamDataAdapter());
    registerAdapter(PurchasedTipAdapter());
    registerAdapter(SceneItemTypeAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(AppLogAdapter());
    registerAdapter(ChatTypeAdapter());
    registerAdapter(ConnectionAdapter());
    registerAdapter(CustomThemeAdapter());
    registerAdapter(DashboardElementAdapter());
    registerAdapter(HiddenSceneAdapter());
    registerAdapter(HiddenSceneItemAdapter());
    registerAdapter(HotkeyAdapter());
    registerAdapter(LogLevelAdapter());
    registerAdapter(PastRecordDataAdapter());
    registerAdapter(PastStreamDataAdapter());
    registerAdapter(PurchasedTipAdapter());
    registerAdapter(SceneItemTypeAdapter());
  }
}
